name: flutterrestaurant
description: A new Flutter restaurant application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.7.0+18
publish_to: none

# CCV 2.7 = 2.7.0+18
# CCV 2.6 = 2.6.0+17
# CCV 2.5 = 2.5.0+16
# CCV 2.4 = 2.4.0+15
# CCV 2.2 = 2.3.0+14
# CCV 2.1 = 2.2.0+13
# CCV 2.1 = 2.1.0+12
# CCV 2.0 = 2.0.0+11
# CCV 1.9 = 1.9.0+10
# CCV 1.8 = 1.8.0+9
# CCV 1.7 = 1.7.0+8
# CCV 1.6 = 1.6.0+7
# CCV 1.5 = 1.5.0+6
# CCV 1.4 = 1.4.0+5
# CCV 1.3 = 1.3.0+4
# CCV 1.2 = 1.2.0+3
# CCV 1.1 = 1.1.0+2
# CCV 1.0 = 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: 
  http: 
  provider:  
  # connectivity: 

  # cached_network_image:  
  theme_manager: 
  flutter_map:  
  image_picker:  

  easy_localization: 
  latlong2:  
  # flutter_paystack: 1.0.5

  sembast:  
  path_provider: 
  # intl: 0.19.0
  shimmer:  
  url_launcher:  
  carousel_slider:  
  firebase_core:  
  firebase_core_platform_interface: 
  firebase_messaging: 
  firebase_auth:
  google_mobile_ads:  
  
  google_sign_in: 
  google_maps_flutter:  
  flutter_facebook_auth:  
  photo_view:  
  flutter_speed_dial:  
  dio: 
  progress_dialog_null_safe:  
  flutter_braintree: 
  launch_review: 
  package_info_plus:  
  fluttericon: 
  flutter_stripe: 
  flutter_credit_card: 
  fluttertoast:  
  permission_handler:  
  permission_handler_platform_interface:  
  the_apple_sign_in:  
  omni_datetime_picker: ^1.1.0
  geolocator:   # Sticked with 7.6.2 for now. If app support android 12, need to update this lib
  geocoding: 
  quiver:
  razorpay_flutter:  
  change_app_package_name: ^1.2.0
  flutter_widget_from_html:  
  flutter_native_image:  
  group_radio_button:  
  # flutter_datetime_picker: 
  # flutter_paystack:  
  flutter_statusbarcolor_ns:  
  share_plus:  
  firebase_dynamic_links: 
  map_launcher:  
  flutter_svg:  
  flutterwave_standard:   # Migrate from flutterwave: (no longer support)
  firebase_crashlytics:  


dependency_overrides:
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_local_notifications:
  #  path: lib/utils/local_noti/

  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/placeholder_image.png
   - assets/
   - myImages/
   - assets/langs/ar-DZ.json
   - assets/langs/en-US.json
   - assets/langs/hi-IN.json
   - assets/langs/de-DE.json
   - assets/langs/es-ES.json
   - assets/langs/fr-FR.json
   - assets/langs/id-ID.json
   - assets/langs/it-IT.json
   - assets/langs/ja-JP.json
   - assets/langs/ko-KR.json
   - assets/langs/ms-MY.json
   - assets/langs/pt-PT.json
   - assets/langs/ru-RU.json
   - assets/langs/th-TH.json
   - assets/langs/tr-TR.json
   - assets/langs/zh-CN.json
   - assets/images/verify_email_icon.jpg
   - assets/images/baseline_feature_circle_24.png
   - assets/images/baesline_access_time_black_24.png
   - assets/images/baseline_check_green_24.png
   - assets/images/baseline_graph_black_24.png
   - assets/images/baseline_price_down_black_24.png
   - assets/images/baseline_price_up_black_24.png
   - assets/images/empty_basket.png
   - assets/images/empty_fav.png
   - assets/images/salad.png
   - assets/images/burger.png
   - assets/images/fs_android_3x.png
   - assets/images/baseline_percent_tag_orange_24.png
   - assets/images/baseline_empty_item_grey_24.png
   - assets/images/home_icon/discount_products.png
   - assets/images/home_icon/easy_payment.png
   - assets/images/home_icon/featured_products.png
   - assets/images/home_icon/free_download.png
   - assets/images/delivery_car_img.png
   - assets/images/trending.png
   - assets/images/user_default_photo.png
   - assets/images/chat.png
   - assets/images/seo.png
   - assets/images/upload.png
   - assets/images/slider 1.svg
   - assets/images/slider 2.svg
   - assets/images/slider 3.svg
   - assets/images/slider 3.svg
   - assets/images/demo_alert.png


   



   
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
